# Generated by Django 2.2.16 on 2021-12-04 11:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EditingRight",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Право на редактирование",
                "verbose_name_plural": "Права на редактирование",
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=256, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "address",
                    models.CharField(max_length=256, verbose_name="Адрес"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "editors",
                    models.ManyToManyField(
                        through="api.EditingRight", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Организация",
                "verbose_name_plural": "Организации",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=30, verbose_name="Имя"),
                ),
                (
                    "patronymic",
                    models.CharField(max_length=30, verbose_name="Отчество"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=30, verbose_name="Фамилия"),
                ),
                (
                    "position",
                    models.CharField(max_length=256, verbose_name="Должность"),
                ),
                (
                    "work_number",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the E.123 format.",
                                regex="^\\+(?:[0-9] ?){6,14}[0-9]$",
                            )
                        ],
                        verbose_name="Рабочий номер телефона",
                    ),
                ),
                (
                    "private_number",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the E.123 format.",
                                regex="^\\+(?:[0-9] ?){6,14}[0-9]$",
                            )
                        ],
                        verbose_name="Личный номер телефона",
                    ),
                ),
                (
                    "fax",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the E.123 format.",
                                regex="^\\+(?:[0-9] ?){6,14}[0-9]$",
                            )
                        ],
                        verbose_name="Факс",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workers",
                        to="api.Organization",
                        verbose_name="Организация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
            },
        ),
        migrations.AddField(
            model_name="editingright",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="api.Organization",
                verbose_name="Организация",
            ),
        ),
        migrations.AddField(
            model_name="editingright",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="editing_rights",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddConstraint(
            model_name="editingright",
            constraint=models.UniqueConstraint(
                fields=("user", "organization"), name="unique_editing_right"
            ),
        ),
    ]
