# Generated by Django 2.2.16 on 2021-12-05 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="editingright",
            name="unique_editing_right",
        ),
        migrations.RemoveField(
            model_name="editingright",
            name="user",
        ),
        migrations.AddField(
            model_name="editingright",
            name="editor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="editing_rights",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь с правом редактирования",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="editingright",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="editing_rights",
                to="api.Organization",
                verbose_name="Организация",
            ),
        ),
    ]
