# Generated by Django 2.2.16 on 2021-12-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_auto_20211205_1028"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="editingright",
            constraint=models.UniqueConstraint(
                fields=("editor", "organization"), name="org_editors"
            ),
        ),
    ]
