# Generated by Django 2.2.16 on 2021-12-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_auto_20211206_1742"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="worker",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="worker",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="worker",
            name="patronymic",
        ),
        migrations.AddField(
            model_name="worker",
            name="full_name",
            field=models.CharField(
                default=1, max_length=60, verbose_name="ФИО"
            ),
            preserve_default=False,
        ),
    ]
